---
title: "BLUP_calculation"
author: "SUBHASH MAHAMKALI"
date: "12/25/2023"
output: NULL
DATA : "sorghum_seedling"
Phenotypic Traits : "plant seedling height, leaf count, shoot dry weight, shoot fresh weight"
---

### path normalization

```{r setup}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('..//')) 
```

### load required R packages

```{r}
#install.packages("lme4")
#install.packages("readxl")
#install.packages("openxlsx")
#install.packages("dplyrx")
#install.packages("tidyr")
library(lme4)
library(readxl)
library(openxlsx)
library(dplyr)
library(tidyr)
```

### Setting input files and subsetting

```{r}
#data <- read.csv("data/PH_hong.csv")
data$Pedigree <- gsub("PI ", "PI", data$Pedigree)

# Convert all plant_height_r_ columns to numeric, handling non-numeric values gracefully
data <- data %>%
  mutate(across(starts_with("plant_height_r_"), ~ as.numeric(as.character(.)), .names = "{.col}_numeric"))

# After the conversion, check if there are still any non-numeric columns and attempt conversion again if necessary
data <- data %>%
  mutate(across(starts_with("plant_height_r_"), ~ ifelse(is.na(as.numeric(.)), NA, as.numeric(.)), .names = "{.col}_numeric"))
data$plant_height_rep_3 <- as.numeric(data$plant_height_rep_3)

# Changing the structure of the data for the ease of analysis
# Note: Ensure the cols parameter in pivot_longer matches the new column names after conversion if they were changed
data <- pivot_longer(data, cols = starts_with("plant_height_r"), names_to = "replicate", values_to = "height")
data <- filter(data, Treatment == "HN")
data$height<- as.numeric(data$height)

```

### model for blup calculation

```{r}
data$Treatment = factor(data$Treatment)
data$Bench = factor(data$Bench)
data$Row = factor(data$Row)
data$Column = factor(data$Column)
data$Pot_id = factor(data$Pot_id)
data$Pedigree = factor(data$Pedigree)
data$replicate = factor(data$replicate)


#Mprevious model used

#blp = lmer(y ~ 1 + (1 |Pedigree) + (1 |Genotype) + (1 |Bench) + (1|Row) + (1|`Column(Bench)`) + (1|`Block(Bench)`), data=data, 
           #control=lmerControl(check.nobs.vs.nlev = "ignore",
                               #check.nobs.vs.rankZ = "ignore",
                               #check.nlev.gtr.1 = "ignore",
                               #check.nobs.vs.nRE="ignore"))


#model with pedigree as random effects for BLUPS.

model <- lmer(height ~ 1 + (1|Pedigree), data = data)

#model <- lmer(height ~ 1 + (1|Pedigree) + (1|Row) + (1| Column) + (1| Pot_id), data = data)

x=summary(model)

blups= ranef(model)
names(blups)
lines=blups$Pedigree+model@beta[1]
bl=as.data.frame(unique(data[,1]))
colnames(bl)="id"
blp.out=data.frame(id=rownames(lines),model=lines)

colnames(blp.out)[2]="height_BLUP"
bl=merge(bl,blp.out,by=1,all=T)


#to check the fitness of the model.
plot(resid(model) ~ fitted(model), 
     xlab = "Fitted values", ylab = "Residuals")
abline(h = 0, col = "red")
```
### output of the blups calculated files 
```{r}
write.table(bl,file="output/USING_NEW_MODEL/PH_HN.txt",row.names = F,quote = F,sep="\t")
```

