---
title: "2.bal_visualization"
author: "subhash"
date: "2025-08-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
# Read file
d <- fread("/Users/subhashmahamkali/Downloads/chr1.B2_stat.txt",
           header = TRUE, data.table = FALSE)
# Add chromosome column
d$chr <- 1
d <- d[, c("chr", names(d)[names(d) != "chr"])]
d=d[,c(1,2,4)]
d=d[order(d[,1],d[,2]),]
thr <- quantile(d[,3], 0.99)
d$pos_Mb <- d$physPos / 1e6
d[,2] <- d[,2] / 1e6

plot(d[,2], d[,3],
     bty = "l", xlim = c(0, 0.03),
     xlab = "", ylab = "", font.lab = 2)
mtext("Chromosome:1", side=1, line=2, font=2, cex=1)
mtext("B2", side = 2, line = 2, font = 2, cex = 1)
segments(x0=0, x1=720, y0=thr, y1=thr, col="red", lty=2, lwd=2)
```

# generating manhattan plot (style) for the B2 score stats on wild population

```{r}
library(data.table)
#install.packages("R.utils")
library(R.utils)

d=fread("/Users/subhashmahamkali/Downloads/1.miscellaneous/all_chr_merged_with_chr.B2.txt.gz", header=T,data.table=F)
d=d[,c(7,1,3)]
d[,3] <- as.numeric(d[,3])
thr <- quantile(d[,3], 0.99, na.rm = TRUE)
thr
#831.4045
ch=fread("/Users/subhashmahamkali/Downloads/1.miscellaneous/sorghum_project/positive_selection/sorg.chr_length_V5.txt", header=T,data.table=F)
sub[,2] <- as.numeric(sub[,2])
d[,1]  <- as.numeric(d[,1])   # chromosome column
d[,2]  <- as.numeric(d[,2])   # position column
d[,3]  <- as.numeric(d[,3])
ch[,4] <- as.numeric(ch[,4])

dd=NULL
for (k in 1:10){sub=subset(d,d[,1]==k)
sub[,2]=sub[,2]+ch[k,4]
dd=rbind(dd,sub)}
#adjust the genomic positiosn for all chromosomes continuesly 
dd$physPos <- dd[,2] / 1e6 
#converts basepairs to megabase
col=ifelse(dd[,1]%%2==1,"#00000066","#BEBEBE99")
dd_filtered <- dd[dd$LR < 0, ]

midpoints <- sapply(1:10, function(k) {
  mean(range(dd[dd[,1] == k, 2], na.rm=TRUE)) / 1e6
})
dd_filt <- dd[dd[,3] >= 0, ]
thr <- quantile(dd_filt[,3], 0.99, na.rm = TRUE)
#831.5203
png("manhattan_w_plot.png", width=4500, height=1500, res=300)
par(mar=c(5,6,4,2))
plot(dd_filt$physPos, dd_filt[,3],
     col = col[dd[,3] >= 0], pch = 16, cex = 0.4,   
     bty = "l", xlim = c(0,717),
     axes = FALSE, xlab = "", ylab = "", font.lab = 2)
# y-axis
axis(2, las=2, tck=-.03, cex.axis=0.8, font.axis=2)
# x-axis: chromosomes
chr_breaks <- seq(0, 717, length.out=11)
midpoints <- (head(chr_breaks,-1) + tail(chr_breaks,-1)) / 2
axis(1, at=midpoints, labels=1:10, cex.axis=1.2, font.axis=2)
# threshold line
segments(x0=0, x1=720, y0=thr, y1=thr, col="red", lty=2, lwd=2)
# labels
mtext("B2", side=2, line=3, font=2, cex=1.5)
mtext("Chromosome", side=1, line=2.8, font=2, cex=1.5)
mtext("Balancing selection:wild population", side=3, line=0.5, font=2, cex=1, adj=1)
dev.off()

```

# Generating figure for the improved population 

```{r}
library(data.table)
library(R.utils)
#install.packages("R.utils")
d=fread("/Users/subhashmahamkali/Downloads/1.miscellaneous/imp_chr_merged_with_chr.B2.txt.gz", header=T,data.table=F)
d=d[,c(7,1,3)]
d[,3] <- as.numeric(d[,3])
thr <- quantile(d[,3], 0.99, na.rm = TRUE)
ch=fread("/Users/subhashmahamkali/Downloads/1.miscellaneous/sorghum_project/positive_selection/sorg.chr_length_V5.txt", header=T,data.table=F)
#sub[,2] <- as.numeric(sub[,2])
ch[,4]  <- as.numeric(ch[,4])
d[,1]  <- as.numeric(d[,1])   # chromosome column
d[,2]  <- as.numeric(d[,2])   # position column
d[,3]  <- as.numeric(d[,3])
#ch[,4] <- as.numeric(ch[,4])

dd=NULL
for (k in 1:10){sub=subset(d,d[,1]==k)
sub[,2]=sub[,2]+ch[k,4]
dd=rbind(dd,sub)}
#adjust the genomic positiosn for all chromosomes continuesly 
dd$physPos <- dd[,2] / 1e6 
#converts basepairs to megabase
col=ifelse(dd[,1]%%2==1,"#00000066","#BEBEBE99")
dd_filtered <- dd[dd$LR < 0, ]

midpoints <- sapply(1:10, function(k) {
  mean(range(dd[dd[,1] == k, 2], na.rm=TRUE)) / 1e6
})
dd_filt <- dd[dd[,3] >= 0, ]
thr <- quantile(dd_filt[,3], 0.99, na.rm = TRUE)
#1682.746
png("manhattan_i_plot.png", width=4500, height=1500, res=300)
par(mar=c(5,6,4,2))
plot(dd_filt$physPos, dd_filt[,3],
     col = col[dd[,3] >= 0], pch = 16, cex = 0.4,   
     bty = "l", xlim = c(0,717),
     axes = FALSE, xlab = "", ylab = "", font.lab = 2)
# y-axis
axis(2, las=2, tck=-.03, cex.axis=0.8, font.axis=2)
# x-axis: chromosomes
chr_breaks <- seq(0, 717, length.out=11)
midpoints <- (head(chr_breaks,-1) + tail(chr_breaks,-1)) / 2
axis(1, at=midpoints, labels=1:10, cex.axis=1.2, font.axis=2)
# threshold line
segments(x0=0, x1=720, y0=thr, y1=thr, col="red", lty=2, lwd=2)
# labels
mtext("B2", side=2, line=3, font=2, cex=1.5)
mtext("Chromosome", side=1, line=2.8, font=2, cex=1.5)
mtext("Balancing selection:imp population", side=3, line=0.5, font=2, cex=1, adj=1)
dev.off()
```

