---
title: "nucleotide diversity"
author: "subhash"
date: "2025-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash}
# Wild
vcftools --vcf /work/jyanglab/subhash/sorgsd/bal_s/wild_50_samples.recode.vcf \
  --window-pi 10000 --window-pi-step 10000 \
  --out /work/jyanglab/subhash/sorgsd/bal_s/pi/wild

# Landrace
vcftools --vcf /work/jyanglab/subhash/sorgsd/bal_s/landraces.recode.vcf \
  --window-pi 10000 --window-pi-step 10000 \
  --out /work/jyanglab/subhash/sorgsd/bal_s/pi/land

# Improved
vcftools --vcf /work/jyanglab/subhash/sorgsd/bal_s/imp_129_samples.recode.vcf \
  --window-pi 10000 --window-pi-step 10000 \
  --out /work/jyanglab/subhash/sorgsd/bal_s/pi/imp

```

```{bash}
PI_DIR=/work/jyanglab/subhash/sorgsd/bal_s/pi
PLOT=/work/jyanglab/subhash/sorgsd/bal_s/pi/plot

# to BED (0-based start, keep N_VARIANTS)
awk 'NR>1{print $1,$2-1,$3,$5,$4}' OFS='\t' $PI_DIR/wild.windowed.pi > $PLOT/wild.pi.10kb.withN.bed
awk 'NR>1{print $1,$2-1,$3,$5,$4}' OFS='\t' $PI_DIR/land.windowed.pi > $PLOT/land.pi.10kb.withN.bed
awk 'NR>1{print $1,$2-1,$3,$5,$4}' OFS='\t' $PI_DIR/imp.windowed.pi  > $PLOT/imp.pi.10kb.withN.bed

W_PEAK=/work/jyanglab/subhash/sorgsd/bal_s/3.input/wild/wild.top1.ext5k.bed
L_PEAK=/mnt/nrdstor/jyanglab/subhash/datasets/3.results/B2/land.top1.ext5k.bed
I_PEAK=/work/jyanglab/subhash/sorgsd/bal_s/3.input/imp/imp.top1.ext5k.bed

cd $PLOT
bedtools intersect -wa -a wild.pi.10kb.withN.bed -b $W_PEAK | awk 'BEGIN{OFS="\t"}{print $0,"PEAK","Wild"}' > wild.pi.peak.tsv
bedtools intersect -v  -a wild.pi.10kb.withN.bed -b $W_PEAK | awk 'BEGIN{OFS="\t"}{print $0,"BACKGROUND","Wild"}' > wild.pi.bg.tsv
cat wild.pi.peak.tsv wild.pi.bg.tsv > wild_labeled_pi_withN.txt

bedtools intersect -wa -a land.pi.10kb.withN.bed -b $L_PEAK | awk 'BEGIN{OFS="\t"}{print $0,"PEAK","Landrace"}' > land.pi.peak.tsv
bedtools intersect -v  -a land.pi.10kb.withN.bed -b $L_PEAK | awk 'BEGIN{OFS="\t"}{print $0,"BACKGROUND","Landrace"}' > land.pi.bg.tsv
cat land.pi.peak.tsv land.pi.bg.tsv > land_labeled_pi_withN.txt

bedtools intersect -wa -a imp.pi.10kb.withN.bed -b $I_PEAK | awk 'BEGIN{OFS="\t"}{print $0,"PEAK","Improved"}' > imp.pi.peak.tsv
bedtools intersect -v  -a imp.pi.10kb.withN.bed -b $I_PEAK | awk 'BEGIN{OFS="\t"}{print $0,"BACKGROUND","Improved"}' > imp.pi.bg.tsv
cat imp.pi.peak.tsv imp.pi.bg.tsv > imp_labeled_pi_withN.txt

```


```{r}
getwd()
#"/work/jyanglab/subhash/sorgsd/bal_s/pi/plot"
library(dplyr); library(ggplot2); library(readr)

read_pi <- function(path){
  # chr start end pi n_vars SET POP
  read_tsv(path, col_names = c("chr","start","end","pi","n_vars","SET","POP"), show_col_types = FALSE)
}

pi_all <- bind_rows(
  read_pi(file.path("wild_labeled_pi_withN.txt")),
  read_pi(file.path("land_labeled_pi_withN.txt")),
  read_pi(file.path("imp_labeled_pi_withN.txt"))
) %>% filter(is.finite(pi)) %>%
  mutate(SET=factor(SET, levels=c("BACKGROUND","PEAK")),
         POP=factor(POP, levels=c("Improved","Landrace","Wild")))

meds_pi <- pi_all %>% group_by(POP, SET) %>% summarise(med=median(pi), .groups="drop")

stats_pi <- pi_all %>%
  group_by(POP) %>%
  summarise(
    n_peak   = sum(SET == "PEAK"),
    n_bg     = sum(SET == "BACKGROUND"),
    med_peak = median(pi[SET == "PEAK"], na.rm = TRUE),
    med_bg   = median(pi[SET == "BACKGROUND"], na.rm = TRUE),
    p_wilcox = wilcox.test(pi[SET == "PEAK"],
                           pi[SET == "BACKGROUND"])$p.value,
    .groups = "drop"
  )

stats_pi
```
# A tibble: 3 × 6
  POP      n_peak  n_bg med_peak  med_bg  p_wilcox
  <fct>     <int> <int>    <dbl>   <dbl>     <dbl>
1 Improved    953 63413  0.00324 0.00164 1.58e- 90
2 Landrace   1126 63432  0.00504 0.00186 1.85e-265
3 Wild       1582 63360  0.00731 0.00401 1.21e-245


```{r}
library(ggsignif)  # make sure this is installed
pi_all$POP <- factor(pi_all$POP, levels = c("Wild", "Landrace", "Improved"))


# medians already computed as meds_pi
p_pi <- ggplot(pi_all, aes(SET, pi, fill=SET)) +
  geom_violin(trim=TRUE, width=.9, alpha=.9, color="black") +
  geom_boxplot(width=.15, outlier.shape=NA, color="black") +
  geom_text(data=meds_pi, aes(SET, med, label=sprintf("%.3g", med)),
            vjust=-0.8, size=3, fontface="bold", inherit.aes=FALSE) +
  facet_wrap(~POP, nrow=1, scales="fixed") +
  scale_fill_manual(values=c(BACKGROUND="grey75", PEAK="#f7a600")) +
  labs(x=NULL, y="Nucleotide diversity (π)") +
  theme_minimal(base_size=14) +
  theme(
    legend.position="none",
    strip.text=element_text(face="bold", size=16),
    axis.text.x=element_text(face="bold")
  ) +
  geom_signif(
    comparisons=list(c("BACKGROUND","PEAK")),
    map_signif_level=TRUE,
    test="wilcox.test",
    step_increase=0.1
  )

p_pi

ggsave("pi_violin_signif.png", p_pi, width=11, height=4, dpi=600)


```

