---
title: "scripts for variant summary and plotting"
author: "subhash and Jinliang"
date: "2024-07-05"
data: "whole genome sequencing of sorghum association panel - trimmed reads from #400 individuals"
output: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/work/jyanglab/subhash/variant_calling")
```



```{bash}

#calculating basic statistics
#--freq to calculate allele freequency
#--missing to calculate missing rate
#--hardy to calculate heterozygosity rate 

ml plink2
#creating bed file from vcf
plink2 --vcf /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/SAP_V5_annotate.vcf --make-bed --out /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/SAP_v5

plink2 --bfile /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/SAP_v5 --freq alt1bins=0.01,0.02,0.03,0.04,0.05,0.1,0.2,0.3,0.4  --missing --hardy  --out /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.basic_stat

#filtering of vcf files using maf and missing rate from plink2.0
#--maf to filter minor allele freequency
#--geno to filter missing rate from vcf file

plink2 --bfile /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/SAP_v5 --maf 0.05 --geno 0.3 --make-bed --out /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.stat_filter/SAP_V5_filtered

#for filtering heterozygosity there is no direct function in plink2.0
# so I have obtained seperate file of observed heterozygosity from --hardy function using following code
#calculated heterozygosity using plink2.0 function -hardy which gives observed heterozygosity in column 8.

awk '$8 < 0.1 {print $2}'  /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.basic_stat/1.basic_stat.hardy > /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/0.1_het.txt

#now this 0.1_het.txt contains ID with <0.1 heterozygosity.
#here SAP filtered is  maf >0.05 and geno <30%

plink2 -bfile /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.stat_filter/SAP_V5_filtered -extract /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/0.1_het.txt -make-bed -out /work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.stat_filter/1.het_filter/het_0.1_SAP

#this final filtered data contains variants with maf >/=0.05 and missing rate of <30% and heterozygosity with <0.1
```

### generating the graphs from basic statistics.

```{r}
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("data.table")
library(tidyverse)
library(ggplot2)
library(data.table)

#all the output files are otained from plink2.0    allele frequency = --freq , missing rate = --misssing  
#from PLINK2.0
#reading the data frame
var_freq <- read_delim("/work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.basic_stat/1.basic_stat.afreq", delim = "\t") 
#data
head(var_freq)
#calculating refrence allele frreequency since plink2.0 has calcuated only alternative allele
var_freq$REF_FREQS <- 1 - var_freq$ALT_FREQS
#minimum freequency of alt or ref
var_freq$maf <- pmin(var_freq$ALT_FREQS, var_freq$REF_FREQS)
#looking at the data frame
head(var_freq) 
# Confirming the minimum and maximum values of maf
min_maf <- min(var_freq$maf)
max_maf <- max(var_freq$maf)
print(paste("Minimum MAF:", min_maf))
print(paste("Maximum MAF:", max_maf))

# Using ggplot to create a histogram of minor allele frequency
maf <- ggplot(var_freq, aes(x = maf)) + 
  geom_histogram(fill = "brown3", color = "black") +
  labs(title = "Minor Allele Frequency_SAP_v5", x = "MAF", y = "Count") + 
  scale_x_continuous(limits = c(0.05, max_maf), breaks = seq(min_maf, by = 0.05)) +
  theme(axis.text.x = element_text(size = 14, face = "bold"),
        axis.text.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 20, face = "bold"))
maf
ggsave("maf_bqsr_filt.png", plot = maf, width = 10, height = 8, dpi = 600)
#plotting the graph of missing rate from plink2.0
var_miss <- read_delim("/work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.basic_stat/1.basic_stat.vmiss", delim = "\t") #reading the data frame
head(var_miss)
#hist(var_miss$F_MISS,breaks = 50) #basic R plotting
vm <- ggplot(var_miss, aes(x = F_MISS)) + 
  geom_histogram(fill = "brown3", color = "black") +
  labs(title = "variant missing rate SAP_V5", x = "missing rate", y = "Count (Variants)") +
  theme(axis.text.x = element_text(size = 14, face = "bold"),
        axis.text.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 20, face = "bold"))

vm
ggsave("vm_bqsr_filt.png", plot = vm, width = 10, height = 8, dpi = 600)

#plotting observed heterozygosity using plink2.0
het = fread("/work/jyanglab/subhash/variant_calling/9.gvcf_to_vcf/4.filtering/1.annotate/1.plink/1.basic_stat/1.basic_stat.hardy")
het <- ggplot(het, aes(x = `O(HET_REF)`)) + 
  geom_histogram(fill = "brown3", color = "black") +
  labs(title = "Heterozygosity rate SAP_V5", x = "Heterozygosity rate", y = "Count (Variants)") +
  theme(axis.text.x = element_text(size = 14, face = "bold"),
        axis.text.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 20, face = "bold"))
het
ggsave("het_bqsr_filt.png", plot = het, width = 10, height = 8, dpi = 600)
```



#### misc!

### to submit the jobs at a specified time

```{r}
# Define the job names
jobs <- c(
  "Chr01_1_5000000vcf.sh",
  "Chr01_5000001_10000000vcf.sh",
  "Chr01_10000001_15000000vcf.sh",
  "Chr01_15000001_20000000vcf.sh",
  "Chr01_20000001_25000000vcf.sh",
  "Chr01_25000001_30000000vcf.sh",
  "Chr01_30000001_35000000vcf.sh",
  "Chr01_35000001_40000000vcf.sh",
  "Chr01_40000001_45000000vcf.sh",
  "Chr01_45000001_50000000vcf.sh",
  "Chr01_50000001_55000000vcf.sh",
  "Chr01_55000001_60000000vcf.sh",
  "Chr01_60000001_65000000vcf.sh",
  "Chr01_65000001_70000000vcf.sh",
  "Chr01_70000001_75000000vcf.sh",
  "Chr01_75000001_80000000vcf.sh",
  "Chr01_80000001_85000000vcf.sh",
  "Chr01_85000001_85112863vcf.sh"
)

# Define the output file
output_file <- "chr01_vcf.txt"

# Open the file for writing
file_conn <- file(output_file, "w")

# Write the commands to the file
for (job in jobs) {
  command <- paste("sbatch -p guest --begin=2024-06-29T09:00:00", job)
  writeLines(command, file_conn)
}

# Close the file connection
close(file_conn)

# Print a message indicating the file has been created
cat("Commands have been written to", output_file, "\n")

```

