---
title: "R Notebook"
output: NULL
date: 02-05-2024
---

### path normalization

```{r setup}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('..//')) 
```


```{r}
# Load necessary libraries
library(readxl)
library(dplyr)
library(ggplot2)

# Read the Excel file
# Replace 'path_to_your_excel_file.xlsx' with the actual path to your Excel file
df <- read.csv("data/Revised_exp_data/PH_Revised.csv")
df$Pedigree <- gsub("PI ", "PI", df$Pedigree)
# Calculate the mean of the three replicates
head(df)
```

# take a quick and dirty look at the data distribution
```{r}
# calculated mean fresh weight
df[, 6:8] <- sapply(df[, 6:8], as.numeric)
mymean <- function(x) mean(x, na.rm=T);
df$mval <- apply(df[,6:8], 1, mymean)
#hist(df[df$Treatment == "HN", ]$mval)

# Plotting the histogram for HN treatment
ggplot(df, aes(x = mval, fill=Treatment)) +
  geom_histogram(binwidth = 0.1) +
  labs(x = "Mean plant height", y = "Frequency", title = "Distribution of Mean plant height (HN)") +
  theme_minimal()

# change the font size
fsize =16
p1 <- ggplot(data=df, aes(x=mval, col= as.factor(Treatment)) ) +
    geom_histogram(bins=100) +
    #geom_density(adjust = 0.8, size=1.5) +
    #facet_wrap(~ trait, scales="free") +
    #scale_fill_manual(values = alpha(c("grey", "red"), .2)) +
    #guides(fill=FALSE) + factor(trait, levels=out$trait)
    labs(title="Distribution of seedling height", y=NULL, fill="Treatment") + 
    xlab("Average seedling height (cm)") + 
    ylab("Freequency") + 
    theme_bw() +
    theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=fsize),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize, face = "bold"),
          plot.title=element_text(size=fsize, face="bold")) + scale_x_continuous(breaks = seq(min(df$mval, na.rm = TRUE), max(df$mval, na.rm = TRUE), by = 3))
p1    


# Set your specific directory path
directory_path <- "graphs/Raw_combined/"
# Specify the filename
filename <- "height.png"
# Combine directory path and filename
full_path <- file.path(directory_path, filename)

# Use ggsave() to save the plot
ggsave(full_path, plot = p1, width = 10, height = 6, dpi = 500)
```



```{r}

#histogram with density plots

p1 <- ggplot(data=df, aes(x=mval, fill=as.factor(Treatment))) +
  geom_histogram(aes(y=..density..), bins=100, alpha=0.7) + 
  geom_density(aes(color= (Treatment)), size=1, alpha=0.5) + 
  labs(title="Distribution of Seedling Height", fill="Treatment") +
  xlab("Average Seedling Height (cm)") +
  ylab("Density") + 
  theme_bw() +
  theme(axis.text=element_text(size=fsize),
        axis.title=element_text(size=fsize, face="bold"),
        legend.title=element_text(size=fsize, face="bold"),
        legend.text=element_text(size=fsize),
        plot.title=element_text(size=fsize, face="bold"))

p1
```


```{r}
data = read.table("DW.txt")
data = na.omit(data)
mean_HN = mean(data$HN)
mean_LN = mean(data$LN)
t_test = t.test(data$HN, data$LN, paired = TRUE)

p <- ggplot(data) +
  geom_density(aes(x = HN, fill = "HN"), alpha = 0.5) + 
  geom_density(aes(x = LN, fill = "LN"), alpha = 0.5) +
  geom_vline(aes(xintercept = mean_HN), linetype = "dashed", color = "red") +
  geom_vline(aes(xintercept = mean_LN), linetype = "dashed", color = "green") +
  scale_fill_manual(values = c("HN" = "red", "LN" = "green")) +
  theme_minimal()+
  labs(title = "PH", x = "cm", y = "Density") +
  theme(plot.title = element_text(face = "bold", size = 16), axis.title.x = element_text(face = "bold", size = 14),
    axis.title.y = element_text(face = "bold", size = 14), axis.text.x = element_text(face = "bold", size = 12), axis.text.y = element_text(face = "bold", size = 12), legend.text = element_text(face = "bold", size = 10), legend.title = element_blank())


sig_label <- ifelse(t_test$p.value < 0.001, '***',
                   ifelse(t_test$p.value < 0.01, '**',
                   ifelse(t_test$p.value < 0.05, '*', 'ns')))

x_position <- mean(c(mean_HN, mean_LN))
y_position <- max(c(density(data$HN)$y, density(data$LN)$y))

# Add the significance label to the plot
p <- p + annotate("text", x = x_position, y = y_position, label = sig_label, size = 6, color ="blue")

# Display the plot
print(p)
```


