---
title: "BLUE_calculation"
author: "SUBHASH MAHAMKALI"
date: "02/15/2024"
output: NULL
DATA : "sorghum_seedling"
Phenotypic Traits : "plant seedling height, leaf count, shoot dry weight, shoot fresh weight"
---

### path normalization

```{r setup}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('..//')) 
```

### load required R packages

```{r}
#install.packages("lme4")
#install.packages("readxl")
#install.packages("openxlsx")
#install.packages("dplyrx")
#install.packages("tidyr")
library(lme4)
library(readxl)
library(openxlsx)
library(dplyr)
library(tidyr)
```

### Setting input files and subsetting

```{r}
data <- read.csv("data/Revised_exp_data/PH_Revised.csv")
data$Pedigree <- gsub("PI ", "PI", data$Pedigree)
data$plant_height_rep_1<- as.numeric(data$plant_height_rep_1)
data$plant_height_rep_2<- as.numeric(data$plant_height_rep_2)
data$plant_height_rep_3<- as.numeric(data$plant_height_rep_3)
data <- pivot_longer(data, cols = starts_with("plant_height_r"), names_to = "replicate", values_to = "height")

data1 <- filter(data, Treatment == "HN")
data2 <- filter(data, Treatment == "LN")

names(data1) [names(data1) == "height"] = "hn_height"
names(data2) [names(data2) == "height"] = "ln_height"

#phenotype = merge(data1, data2, by = "Pedigree")
phe = rbind(data1, data2)
```

### model for blup calculation

```{r}
data$Treatment = factor(data$Treatment)
data$Bench = factor(data$Bench)
data$Row = factor(data$Row)
data$Column = factor(data$Column)
data$Pot_id = factor(data$Pot_id)
data$Pedigree = factor(data$Pedigree)
#mod = lm(height ~ Treatment + Pedigree + Treatment*Pedigree, data = data)
#mod = lm(height ~ Pedigree + Row + Column + Pot_id, data = data1)
mod = lmer(height ~ Pedigree + (1|Row) + (1|Column) + (1|Pot_id), data = data2)
x = summary(mod)
anova = anova(mod)
BLUE <- as.data.frame(fixef(mod))
rownames(BLUE)=gsub("Pedigree","",rownames(BLUE))
BLUE$Pedigree = rownames(BLUE)
BLUE$Pedigree[1] = "PI152651"
HN=data.frame(id=rownames(BLUE),Phe=c(BLUE[1,1],(BLUE[-1,1]+BLUE[1,1])))
HN$id[1] = "PI152651"
write.table(b, file = "data_frame_b.txt", sep = "\t", row.names = TRUE, col.names = TRUE)


LN=data.frame(id=rownames(BLUE),Phe=c(BLUE[1,1],(BLUE[-1,1]+BLUE[1,1])))
LN$id[1] = "PI152651"
write.table(b, file = "data_frame_b.txt", sep = "\t", row.names = TRUE, col.names = TRUE)

```
